In [1]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
import seaborn as sns

In [2]:
fk = pd.read_csv("../dataset/Fake.csv")
tr = pd.read_csv("../dataset/True.csv")

In [3]:
fk.shape, tr.shape

((23481, 4), (21417, 4))

In [4]:
fk.head()

,title,text,subject,date
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017"
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017"
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017"
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017"
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017"

In [5]:
tr.head()

,title,text,subject,date
0,"As U.S. budget fight looms, Republicans flip t...",WASHINGTON (Reuters) - The head of a conservat...,politicsNews,"December 31, 2017"
1,U.S. military to accept transgender recruits o...,WASHINGTON (Reuters) - Transgender people will...,politicsNews,"December 29, 2017"
2,Senior U.S. Republican senator: 'Let Mr. Muell...,WASHINGTON (Reuters) - The special counsel inv...,politicsNews,"December 31, 2017"
3,FBI Russia probe helped by Australian diplomat...,WASHINGTON (Reuters) - Trump campaign adviser ...,politicsNews,"December 30, 2017"
4,Trump wants Postal Service to charge 'much mor...,SEATTLE/WASHINGTON (Reuters) - President Donal...,politicsNews,"December 29, 2017"

In [6]:
fk.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23481 entries, 0 to 23480
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   title    23481 non-null  object
 1   text     23481 non-null  object
 2   subject  23481 non-null  object
 3   date     23481 non-null  object
dtypes: object(4)
memory usage: 733.9+ KB

In [7]:
tr.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21417 entries, 0 to 21416
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   title    21417 non-null  object
 1   text     21417 non-null  object
 2   subject  21417 non-null  object
 3   date     21417 non-null  object
dtypes: object(4)
memory usage: 669.4+ KB

In [8]:
fk = fk.drop(columns=['title','subject','date'])
tr = tr.drop(columns=['title','subject','date'])

In [9]:
fk['label'] = 0
tr['label'] = 1

In [11]:
fk.head()

                                                text  label
0  Donald Trump just couldn t wish all Americans ...      0
1  House Intelligence Committee Chairman Devin Nu...      0
2  On Friday, it was revealed that former Milwauk...      0
3  On Christmas day, Donald Trump announced that ...      0
4  Pope Francis used his annual Christmas Day mes...      0

In [12]:
tr.head()

                                                text  label
0  WASHINGTON (Reuters) - The head of a conservat...      1
1  WASHINGTON (Reuters) - Transgender people will...      1
2  WASHINGTON (Reuters) - The special counsel inv...      1
3  WASHINGTON (Reuters) - Trump campaign adviser ...      1
4  SEATTLE/WASHINGTON (Reuters) - President Donal...      1

In [13]:
fk.isnull().sum()

text     0
label    0
dtype: int64

In [14]:
tr.isnull().sum()

text     0
label    0
dtype: int64

In [15]:
fk.duplicated().sum()

np.int64(6026)

In [16]:
tr.duplicated().sum()

np.int64(225)

In [17]:
fk = fk.drop_duplicates()

In [18]:
tr = tr.drop_duplicates()

In [19]:
fk.duplicated().sum()

np.int64(0)

In [20]:
tr.duplicated().sum()

np.int64(0)

In [21]:
fk.shape

(17455, 2)

In [22]:
tr.shape

(21192, 2)

In [23]:
df = pd.concat([fk,tr], axis=0)

In [24]:
df.head()

                                                text  label
0  Donald Trump just couldn t wish all Americans ...      0
1  House Intelligence Committee Chairman Devin Nu...      0
2  On Friday, it was revealed that former Milwauk...      0
3  On Christmas day, Donald Trump announced that ...      0
4  Pope Francis used his annual Christmas Day mes...      0

In [25]:
df.tail()

                                                    text  label
21412  BRUSSELS (Reuters) - NATO allies on Tuesday we...      1
21413  LONDON (Reuters) - LexisNexis, a provider of l...      1
21414  MINSK (Reuters) - In the shadow of disused Sov...      1
21415  MOSCOW (Reuters) - Vatican Secretary of State ...      1
21416  JAKARTA (Reuters) - Indonesia will buy 11 Sukh...      1

In [26]:
df.shape

(38647, 2)

In [27]:
df = df.sample(frac=1).reset_index(drop=True)

In [28]:
df.head()

                                                text  label
0  WASHINGTON (Reuters) - President Donald Trump’...      1
1  Perhaps the Green Party isn t so useless after...      0
2  An electrical contractor wrote to the 54-year-...      0
3  It s been two days since the Secret Service de...      0
4  LOS ANGELES (Reuters) - Reality star Caitlyn J...      1

In [29]:
df.shape

(38647, 2)

In [30]:
df.isnull().sum()

text     0
label    0
dtype: int64

In [31]:
import re
import nltk
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer

In [32]:
nltk.download("stopwords")

[nltk_data] Downloading package stopwords to C:\Users\Sakshi
[nltk_data]     Yadav\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [33]:
corpus = []
stemmer = PorterStemmer()
stop_words = set(stopwords.words("english"))

In [34]:
import string

In [35]:
for i in range(len(df)):
    # remove non-letters
    review = re.sub('[^a-zA-z]',"",df['text'][i])
    # lowercase
    review = review.lower()
    # tokenization
    review = review.split()
    # stopwords removal + stemming
    review = [ 
        stemmer.stem(word) 
        for word in review 
        if word not in stop_words
    ]
    # join words again
    review = " ".join(review)
    
    corpus.append(review)

In [36]:
X = corpus
y = df["label"]

In [37]:
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import PassiveAggressiveClassifier
from sklearn.metrics import accuracy_score, classification_report

In [38]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [39]:
tfidf = TfidfVectorizer(max_features=5000)

In [40]:
X_train = tfidf.fit_transform(X_train)

In [41]:
X_test = tfidf.transform(X_test)

In [42]:
model = PassiveAggressiveClassifier(max_iter=1000)

In [43]:
model.fit(X_train, y_train)

PassiveAggressiveClassifier()

In [44]:
y_pred = model.predict(X_test)

In [45]:
acc = accuracy_score(y_test, y_pred)
print("Accuracy:", acc)

Accuracy: 0.5739974126778784

In [47]:
y_pred[:5]

array([1, 1, 1, 1, 1])

In [48]:
y_test[:5]

35899    1
23305    0
38276    1
21572    1
4156     0
Name: label, dtype: int64